# POST http://localhost:8080/api/auth/register
# content-type: application/json

# {
#   "email": "email@email.com",
#   "firstName": "first",
#   "lastName": "last",
#   "pseudo": "pseudo",
#   "password": "Password!123",
#   "confirmationPassword": "Password!123",
#   "motivation": "{ type: String, required: true }, motivation, motivation, motivation, motivation, motivation, motivation, motivation",
#   "avatar": "http://urlavatardetest.jpg",
#   "roleId": "67f69e69c92c96c8ff0093df"
# }

POST http://localhost:8080/api/auth/login
content-type: application/json

{
  "email": "email@email.com",
  "password": "Password!123"
}